# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 今天是谁陪餐？

on:
  schedule:
    - cron: '0 22 * * *'

  workflow_dispatch:

jobs:

  who:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Fetch required Go modules
        run:  cd lunch2 && go mod download

      - name: Run it
        env:
          TZ: Asia/Shanghai
          GO_MAIL_FROM: ${{ secrets.GO_MAIL_FROM }}
          GO_MAIL_FROM_PWD: ${{ secrets.GO_MAIL_FROM_PWD }}
          GO_MAIL_TO: ${{ secrets.GO_MAIL_TO }}
        run: cd lunch2 && go run main.go
